// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        buttonContainer: string;
        container: string;
        home: string;
        resetButton: string;
        sessionCountLabel: string;
        startStopButton: string;
        statusLabel: string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
